
services:
      

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - /home/qdrant_data:/qdrant/storage # connecton between the contaainer and the folder for storage
    networks:
      - backend
    restart: unless-stopped
    ports:
      - "6333:6333"

  biohor-chat:
    build: .

    restart: unless-stopped

    volumes:
      - .env/.env

    command: ["sh", "-c", "exec chainlit run app/src/chainlit_webapp/main.py --host 0.0.0.0 --port 8000"]

    networks:
      - backend
    depends_on:
      - qdrant
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  backend:
    name: biohor-net

