[project]
name = "biohorizon-insights-from-nasa-space-biology"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ag-ui-protocol==0.1.9",
]
